### ISSUE TITLE
Wait until element is focused

### ISSUE THREAD

**Issue by WinterSoldier55** [robotframework/Selenium2Library#11]
I added this keyword to my local repository with great success.

```
    @keyword
    def wait_until_element_is_focused(self, locator, timeout=None, error=None):
    """Waits until element specified with 'locator' is focused.

        Key attributes for arbitrary elements are `id` and `name`. See
        `introduction` for details about locating elements.

    """
        def check_focus():
            element = self.find_element(locator)
            try:
                focused = self.browser.execute_script('return document.activeElement;')
            except (IOError, RuntimeError) as err:
                raise AssertionError("Internal Error: '%s'" % (err))
            if not element == focused:
                return error or "ERROR: Element '%s' is not with focus after %s." % (locator, self._format_timeout(timeout))
        self._wait_until_no_error(timeout, check_focus)
```

I previously requested that "Element should be focused" be added to Selenium2Library, which is why I added "Wait until element is focused".

I'm not sure how to successfully make a pull request to get this reviewed. Is it possible to have this reviewed by a dev, and possibly merged to master eventually?

My apologies if this is not standard procedure.

Thanks,
Winter

**Comment by aaltat** [comment]
The Selenium2Library is now days only a wrapper for the SeleniumLibrary, therefore could you move the issue to the SeleniumLibrary issue tracker: https://github.com/robotframework/SeleniumLibrary/issues

Creating enhancement request by using issues is totally fine. Also by a quick look, your idea looks good one. The SeleniumLibrary project has instructions how the enhancement request works: https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst 

But because issue is in wrong issue tracker, U am closing the issue. Please raise new issue in SeleniumLibrary project.
